id: '5714.5987'
title: Azure New Application Credential
description: 'An application may use a certificate or secret string to prove its identity
  when requesting a token. Multiple certificates and secrets can be added for an application
  and an adversary may abuse this by creating an additional authentication method
  to evade defenses or persist in an environment. -- Threat Actor Association: Storm-1283'
logic_format: Splunk
logic: '`get_cloud_data` `get_cloud_data_azure` "Update application" "Certificates
  and secrets management" TERM(success) | table _time, host, user,account, region,
  src_ip, http_user_agent, access_key, user, user_id, identity_type, role, event_name,
  event_category, cloud_service, request_parameters, response, mfa_enabled, permissions,
  identity, action, resource_id, object_id | bin span=1s | stats values(*) as * by
  _time, user '
techniques:
- credential-access:steal application access token
- defense-evasion:valid accounts
technique_id: null
data_category:
- Azure activity logs
references:
- https://www.microsoft.com/security/blog/2020/12/21/advice-for-incident-responders-on-recovery-from-systemic-identity-compromises/
