id: '20715.36907'
title: AWS Security Group Ingress Revoked
description: Detects when an ingress rule has been removed from a security group.
  An ingress rule permits instances to receive traffic from the specified IPv4 or
  IPv6 CIDR address range, or from the instances that are associated with the specified
  destination security groups.
logic_format: snowflake
logic: select * from awscloudtrail where event_time > dateadd(hour, -2, sysdate())
  and to_timestamp(date_part(epoch_second, event_time)) < $latest$ and event_name
  = 'RevokeSecurityGroupIngress'
techniques:
- persistence:account manipulation
technique_id: 
- T1098
data_category:
- AWS CloudTrail logs
references:
- https://unit42.paloaltonetworks.com/sugarcrm-cloud-incident-black-hat/
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RevokeSecurityGroupIngress.html
