id: '9050.16106'
title: 'Okta: Application Modified or Deleted'
description: This use case looks for updates or removals of OKTA applications
logic_format: snowflake
logic: 'select * from okta where event_time > dateadd(hour, -2, sysdate()) and (event_type
  ilike ''application.lifecycle.update'' or event_type ilike ''application.lifecycle.delete'') '
techniques:
- impact:endpoint denial of service
technique_id: null
data_category:
- Application logs
references:
- https://developer.okta.com/docs/reference/api/event-types/#catalog
