id: '1104.1164'
title: Modify sshd_config
description: 'Sshd_config file modification in order to allow a backdoor user to connect.
  The sshd_config file details the different configuration options of the SSH server
  with keyword/argument pairs. -- Threat Actor Association: TeamTNT'
logic_format: Splunk
logic: '`get_endpoint_data` `get_endpoint_data_unix` ((TERM(vi) OR TERM(vim) OR TERM(nano)
  OR TERM(echo) OR TERM(open) OR TERM(visudo)) AND "sshd_config") OR (TERM(ssh) AND
  (TERM(restart) OR TERM(start))) | regex process="(?i)((vi|nano|visudo|echo|open)\s+.+sshd_config)|(ssh\s+(start|restart))|((start|restart)\s+ssh)"
  | table _time, host, user, process, process_* | bin span=600s | stats values(*)
  as * by _time, host | where match(process, "(?i)vi|nano|visudo|echo|open.+sshd_config")
  AND match(process, "(?i)(ssh.+(start|restart))|((start|restart).+ssh)") '
techniques:
- persistence:account manipulation:ssh authorized keys
technique_id:
- T1098.004
data_category:
- Process command-line parameters
- Linux audit logs
references: null
