id: '1104.14721'
title: Modify sshd_config
description: 'Sshd_config file modification in order to allow a backdoor user to connect.
  The sshd_config file details the different configuration options of the SSH server
  with keyword/argument pairs. -- Threat Actor Association: TeamTNT'
logic_format: snowflake
logic: 'select * from crowdstrikefdr_process where event_time > dateadd(hour, -2,
  sysdate()) and (event_platform = ''Lin'' or event_platform = ''Mac'') and ((regexp_like(process,
  ''.*[^a-z](vi|vim|nano|echo|open|visudo)[^a-z].*'', ''i'') and process ilike ''%sshd_config%'')
  OR (regexp_like(process, ''.*[^a-z](ssh)[^a-z].*'', ''i'') and regexp_like(process,
  ''.*[^a-z](start|restart)[^a-z].*'', ''i''))) '
techniques:
- persistence:account manipulation:ssh authorized keys
technique_id:
- T1098.004
data_category:
- EDR Logs
references: null
