id: '5986.14607'
title: Access Common Package Config file
description: 'Adversaries may establish persistence and/or elevate privileges using
  system mechanisms that trigger execution based on specific events. An Adversary
  with access could identify or modify configuration of packages in order to execute
  code and evade defenses. '
logic_format: snowflake
logic: select * from crowdstrikefdr_process where event_time > dateadd(hour, -2, sysdate())
  and event_platform = 'Win' and regexp_like(process, '.*((vi|vim|nano|visudo|edit|copy\\\s+con|cat|more|gc|get-content|type|\\\>\\\>|\\\>)\\\s+.*(requirements\\\.txt|pip\\\.conf|package.json|\\\\.gemspec|gemrc)).*',
  'i')
techniques:
- persistence:event triggered execution
- privilege-escalation:event triggered execution
technique_id: 
- T1546
data_category:
- EDR Logs
references:
- https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
