id: '5986.6346'
title: Access Common Package Config file
description: 'Adversaries may establish persistence and/or elevate privileges using
  system mechanisms that trigger execution based on specific events. An Adversary
  with access could identify or modify configuration of packages in order to execute
  code and evade defenses. '
logic_format: Splunk
logic: '`get_endpoint_data` `get_endpoint_data_unix` (TERM(vi) OR TERM(vim) OR TERM(nano)
  OR TERM(visudo) OR TERM(cat) OR TERM(more) OR TERM(less) OR ">>" OR ">") ("requirements.txt"
  OR "pip.conf" OR "package.json" OR "gemspec" OR "gemrc") | regex process="(?i)(vi|vim|nano|visudo|cat|more|less|\>\>|\>)\s+.+(requirements\.txt|pip\.conf|package.json|\.gemspec|gemrc)"
  | table _time, host, user, process, process_*, type | bin span=1s | stats values(*)
  as * by _time, host '
techniques:
- persistence:event triggered execution
- privilege-escalation:event triggered execution
technique_id: 
- T1546
data_category:
- Process command-line parameters
- Linux audit logs
references:
- https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
