id: '8076.9790'
title: Kubernetes Update Pod Configuration
description: This use case looks for when a pod configuration has been modified with
  kubectl-edit, scale, autoscale, or replace.
logic_format: Splunk
logic: '`get_application_data` `get_application_data_api` ("kubectl-edit" OR TERM(scale)
  OR TERM(autoscale) OR TERM(replace)) verb IN("create", "patch", "update") |regex
  uri="(?i)kubectl\-edit|scale|kubectl\-autoscale|kubectl\-replace" | table _time,
  host, user action, reason, uri, uri_path, status, src_ip, user_group, user_id, user,
  user_agent, event_type, object_*, request_*, response_*, image, container_arguements
  | bin span=1s | stats values(*) as * by _time, src_ip '
techniques:
- defense-evasion:deploy container
- execution:deploy container
technique_id: 
- T1610
data_category:
- API monitoring
references:
- https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/
