id: '8076.14733'
title: Kubernetes Update Pod Configuration
description: This use case looks for when a pod configuration has been modified with
  kubectl-edit, scale, autoscale, or replace.
logic_format: snowflake
logic: 'select * from crowdstrikefdr_process where event_time > dateadd(hour, -2,
  sysdate()) and (event_platform = ''Lin'' or event_platform = ''Mac'') and regexp_like(process,
  ''.*kubectl[^a-z].*'', ''i'') and regexp_like(process, ''.*[^a-z](edit|scale|autoscale|replace)[^a-z].*'',
  ''i'') '
techniques:
- defense-evasion:deploy container
- execution:deploy container
technique_id: null
data_category:
- EDR Logs
references:
- https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/
