id: '15967.23922'
title: PowerShell Modifying Registry Values
description: 'Adversaries may interact with the Windows Registry to hide configuration
  information within Registry keys, remove information as part of cleaning up, or
  as part of other techniques to aid in persistence and execution. This use case detects
  PowerShell commands accessing or modifying the Current User or Local Machine registry
  hives. -- Threat Actor Association: CL-STA-0043 -- Atomics T1059.001 Test #11 Atomics
  T1546.008 Test #1'
logic_format: snowflake
logic: 'select * from crowdstrikefdr_process where event_time > dateadd(hour, -2,
  sysdate()) and to_timestamp(date_part(epoch_second, event_time)) < $latest$ and
  event_platform = ''Win'' and regexp_like(process, ''.*(Invoke-Expression|\\\Wiex\\\W).*'',
  ''i'') and regexp_like(process, ''.*(HKCU|HKLM|HKEY_LOCAL_MACHINE|HKEY_CURRENT_USER).*'',
  ''i'') '
techniques:
- defense-evasion:modify registry
- execution:command and scripting interpreter:powershell
technique_id:
- T1059.001
data_category:
- EDR Logs
references:
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-11---powershell-fileless-script-execution
