id: '1053.1082'
title: Web Application File Upload
description: 'Uploaded files represent a significant risk to applications. The first
  step in many attacks is to get some code to the system to be attacked. Then the
  attack only needs to find a way to get the code executed. Using a file upload helps
  the attacker accomplish the first step. Threat Actor Association: Agrius, APT41,
  FIN13, Lazarus, Magic Hound (aka APT35, Charming Kitten, Phosphorus, and Mint Sandstorm),
  OilRig, PROPHET SPIDER, UNC5221, UTA0178, Volt Typhoon (Bronze Silhouette, Vanguard
  Panda) -- Software Association: AvosLocker, Clop, Cring'
logic_format: Splunk
logic: '`get_web_data` `get_web_data_waf` ((TERM(POST) OR TERM(PUT)) (".php" OR ".jsp"
  OR ".jspx" OR ".py" OR ".asp" OR ".aspx" OR ".asmx" OR ".pl" OR ".ascx" OR "ashx"
  OR "cfm" OR ".cgi" OR ".amf")) | table _time, host, user, src_ip, http_method, uri,
  uri_query, http_referer, http_user_agent, host, http_content_type, site, uri_path,
  action | bin span=1s | stats values(*) as * by _time, site | where match(uri, "(?i)\.(php|jsp|jspx|py|asp|aspx|asmx|pl|ascx|ashx|cfm|cgi|amf)")
  OR match(uri_path, "(?i)\.(php|jsp|jspx|py|asp|aspx|asmx|pl|ascx|ashx|cfm|cgi|amf)")
  | iplocation prefix="src_" src_ip| rename src_Country as src_country '
techniques:
- initial-access:exploit public-facing application
- persistence:server software component:web shell
technique_id:
- T1190
- T1505.003
data_category:
- File monitoring
- Web logs
references: null
